name: Node.js CI

on:
  workflow_run:
    workflows:
      - "Java CI with Maven"
    types:
      - completed

jobs:
  build-and-push-frontend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | \
          docker login \
            --username "${{ secrets.DOCKER_HUB_USERNAME }}" \
            --password-stdin

      - name: Build frontend image
        run: |
          docker build \
            -t "${{ secrets.DOCKER_HUB_USERNAME }}/book-portal-fe:latest" \
            ./book-portal-fe

      - name: Push frontend image
        run: |
          docker push \
            "${{ secrets.DOCKER_HUB_USERNAME }}/book-portal-fe:latest"

      - name: Build proxy image
        run: |
          docker build \
            -t "${{ secrets.DOCKER_HUB_USERNAME }}/book-portal-proxy:latest" \
            ./nginx

      - name: Push proxy image
        run: |
          docker push \
            "${{ secrets.DOCKER_HUB_USERNAME }}/book-portal-proxy:latest"
